easy_admin:
#    design:
#        form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']
    site_name: 'Portfolio'
    design:
        menu:
            - { label: 'Домашняя страница', route: 'homepage' }
            - { entity: 'Post', label: 'Портфолио', icon: 'tag' }
            - User
            - Image
    entities:
        Post:
            class: AppBundle\Entity\Post
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'thumb', type: 'image', base_path: '%app.path.product_images%' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
            show:
                fields:
                    - { property: 'title' }
                    - { property: 'thumb', type: 'image', base_path: '%app.path.product_images%' }
                    - { property: 'content' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'thumbFile', type: 'vich_image' }
                    - { property: 'content' }
                    - { property: 'image' }
        User:
            class: AppBundle\Entity\User

        Image:
            class: AppBundle\Entity\Image
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'name' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'name' }
                    - { property: 'imageFile', type: 'vich_image' }
