vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/posts'

        images:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
